### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by D1WK** [DabDatBass/accreate#4]
How do I use this

**Comment by DabDatBass** [comment]
1. Download version 0.1.2c .zip
2. Extract with either 7-Zip or Windows' unzipper
3. Create a file called "accreate"
4. find "index.js" in the extracted file and move that to the "accreate" file
5. Import when you need to use it!

Version 0.1.3 is getting ready for NPM so that's why i said 0.1.2c.

**Comment by D1WK** [comment]
Thanks!
